### ISSUE TITLE
Project structure and concepts

### ISSUE THREAD

**Issue by Pouya-moh** [Pouya-moh/2R-CSpace#1]
I can think of something like this for the entire project structure:

1. [2R-robot](https://github.com/Pouya-moh/2R-robot) repo for robot model plus goodies (FK, IK, change link ratio, etc). Don't think collision stuff will go here.
2. [2R-GUI](https://github.com/Pouya-moh/2R-GUI) for the GUI and its discussions.
3. [2R-CSapce](https://github.com/Pouya-moh/2R-CSpace) i.e. is this repo, will be the discussion and meta stuff which do not fit directly into other places.

Other repositories that might be necessary are 2R-[obstacle stuff, docs or .io page]. Another important repo will be a deployment repository. I want this to have all the dependencies linked and shipped with it and for all major operating systems for that matter (Linux, MacOS)

fine windows as well...

@volksfest Thoughts?

**Comment by Volksfest** [comment]
Tbh, I wouldn't seperate the structure in different repositories. Well, of course, we could do a whole 2R robot kinematics library independant of anything, legitimating an own repository. But that is the only thing I have in mind here, which could legitimate a seperation. The rest ist not generalized enough to legitimate this work.

**Comment by Pouya-moh** [comment]
Fair enough, I will keep the 2R-robot and simplify the rest.
